function zoomedImg(cdata1, cdata2)
%CREATEFIGURE(CDATA1,CDATA2)
%  CDATA1:  image cdata
%  CDATA2:  image cdata

%  Auto-generated by MATLAB on 06-Nov-2012 18:40:08

% Create figure
figure1 = figure;
colormap('gray');

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1,'YDir','reverse',...
    'PlotBoxAspectRatio',[16 16 1],...
    'Layer','top',...
    'DataAspectRatio',[1 1 1],...
    'CLim',[0 1]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[9.10543497631375 25.1054349763137]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[9.93772395918574 25.9377239591857]);
box(subplot1,'on');
hold(subplot1,'all');

% Create image
image(cdata1,'Parent',subplot1,'CDataMapping','scaled');

% Create title
title('Original image');

% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1,'YDir','reverse',...
    'PlotBoxAspectRatio',[16 16 1],...
    'Layer','top',...
    'DataAspectRatio',[1 1 1],...
    'CLim',[0 1]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[8.81447922987358 24.8144792298736]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[10.0670886792574 26.0670886792574]);
box(subplot2,'on');
hold(subplot2,'all');

% Create image
image(cdata2,'Parent',subplot2,'CDataMapping','scaled');

% Create title
title('Unsharp mask');

